### ISSUE TITLE
[Term] Reverse Display Colors mode (CSI ? 5 h/l, DECSCNM)

### ISSUE THREAD

**Issue by o-sdn-o** [netxs-group/vtm#152]
The mode in which all the colors of the viewport are inverted, something just like XOR logic in monochrome terminals.

**Comment by klamonte** [comment]
Reverse video in most terminals is handled as a final "flip foreground/background color" right before the cell is emitted to screen.  So if you reverse video, scroll a line into the scrollback, un-reverse (so normal again) and look in the scrollback, the line(s) are not reversed anymore.  It's a screen attribute rather than a line or character attribute.  That might make things easier.

**Comment by o-sdn-o** [comment]
You're right, here swapping between foreground and background would be a more consistent solution than color inversion. Thanks for the tip 👌

**Comment by o-sdn-o** [comment]
Oops, I just now realized that I should not choose the inversion method, I should only change the invert bit, thanks again.
