### ISSUE TITLE
Capturing area into internal clipboard (Ctrl+MiddleDrag) copies ASNI-escape sequences too.

### ISSUE THREAD

**Issue by neoh4x0r** [netxs-group/vtm#216]
Selecting an area to copy via Ctrl+MiddleDrag does not seem to copy text in the same way as (LeftDrag + Rightclick)

The text: **./externals** is copied/pasted as **;2;16;16;16m;2;248;242m./externals**

![2022-05-06_01-20](https://user-images.githubusercontent.com/7200584/167071828-489ab652-1295-4554-a1a2-14b9ff80cf5f.png)
![2022-05-06_01-21](https://user-images.githubusercontent.com/7200584/167071830-e1bfabe7-0337-4bec-9319-3f47f57e0e5c.png)

**Comment by o-sdn-o** [comment]
Capturing using `Ctrl+MiddleDrag`(or `Ctrl+RightDrag`) was originally designed as copying a fragment of an arbitrary area of the entire screen(viewport, desktop environment) with all SGR attributes. In order to capture plaintext inside the terminal, you need to use selection in `Plaintext` mode and `LeftDrag` + `RightClick`.

**Comment by o-sdn-o** [comment]
I will make copy mode with `Ctrl+MiddleDrag/RightDrag`) configurable. In the settings, you can specify whether to copy SGR-attributes along with the text or not.

**Comment by o-sdn-o** [comment]
There is no need to configure the copy mode/format for the desktop environment. You can recursively connect to the environment through the built-in terminal and copy any desktop region in any supported format.
