### ISSUE TITLE
Make clipboard buffer preview configurable

### ISSUE THREAD

**Issue by o-sdn-o** [netxs-group/vtm#266]
We need to add a config option to disable clipboard preview.

To disable the clipboard buffer preview just make the following config in ~/.config/vtm/settings.xml:
```xml
<config>
    <client>
        <clipboard>
            <preview enabled=false size=80x25 />
        </clipboard>
    </client>
</config>
```

**Comment by o-sdn-o** [comment]
Hi @AloisKraus! Now you can disable clipboard preview (copied text hovers over the mouse cursor). See description above for details.

**Comment by AloisKraus** [comment]
@o-sdn-o: I have tried it. Works perfectly. 

```
<client>
    <clipboard>
        <preview enabled=false size=80x25 />
     </clipboard>
```

Great work again. Are hotkeys to copy/paste like the standard windows keys Ctrl+C for copy and Ctrl+V for paste already there? I have looked a bit but not found anything in the code so far.

**Comment by o-sdn-o** [comment]
Thanks!

> Are hotkeys to copy/paste like the standard windows keys Ctrl+C for copy and Ctrl+V for paste already there?

Unfortunately keyboard shortcuts are not supported yet. I will start to implement this right after the xml-config #234 implementation is completed. Related to #86.

**Comment by o-sdn-o** [comment]
By intent, the clipboard is cleared by pressing the Left+Right mouse buttons. The preview was made to improve security when working with the clipboard, since any program in the terminal can set arbitrary (unsafe) contents of the clipboard.

**Comment by AloisKraus** [comment]
@o-sdn-o: Preview is nice in theory, but in practice I type in the terminal and some text is replaced by the hovered mouse with something copied. Security is also an issue if you replace text while the mouse is hovering and you display wrong output. If the data values are critical you might run into much bigger issues by e.g. formatting the wrong hard drive just because the clipboard security feature was overlaying something which looked like the partition to drive mapping, just the wrong one.

**Comment by o-sdn-o** [comment]
You are right, even for the case of enabled preview, it might also make sense to add auto-hide by mouse inactivity timeout and also add highlighting to make it look like a tooltip.
