### ISSUE TITLE
Block running new vtm instance in Direct-VT

### ISSUE THREAD

**Issue by Segilmez06** [netxs-group/vtm#271]
If I try to execute vtm in Direct-VT, this happens:

https://user-images.githubusercontent.com/33354718/200143621-f9312af7-bde1-4b5e-91c8-07f5c6267850.mp4

It'll be great if blocks and alerts.

**Comment by o-sdn-o** [comment]
This behavior is due to the fact that vtm is a multi-user/multi-seat environment. Any number of participants can be connected, whether local or remote via SSH

https://user-images.githubusercontent.com/11535558/200152898-f2ea19c3-6d99-4dfa-87b0-8f0e4ddfe36b.mp4

Here we need to come up with a way to detect a recursive connection. To do this, apparently, it is necessary to generate some unique session id, something like a GUID, excluding intersections with remote session ids.

**Comment by o-sdn-o** [comment]
Note, since the vtm environment is borderless, support for recursive connections was designed to be able to view regions of the desktop environment that are outside the viewport.

**Comment by o-sdn-o** [comment]
Example of recursive connection usage

https://user-images.githubusercontent.com/11535558/200163323-12d4fd0f-d68c-4fea-96b3-2616f6bce785.mp4

**Comment by o-sdn-o** [comment]
Feel free to reopen this issue if the recursive connection behaves uncontrollably and unpredictably.

**Comment by o-sdn-o** [comment]
FYU, with a recursive connection, multiple nested visible artefacts are just duplicate images, nothing more, although it looks like uncontrolled endless new connections.
