### ISSUE TITLE
Make it ready

### ISSUE THREAD

**Issue by abotsis** [netxs-group/VTM#31]
Problem Description: Source tree says it's not ready.

Expected Behavior: There's code in the source tree that builds.

**Comment by evandrix** [comment]
demo `ssh vtm@netxs.online` looks like a real un-usable mess -.-

**Comment by o-sdn-o** [comment]
> demo `ssh vtm@netxs.online` looks like a real un-usable mess -.-

What terminal emulator are you using?

**Comment by 0Karakurt0** [comment]
@abotsis  Where have you found code? I don't see any... And akk files are almost empty

**Comment by Nanoc-ice** [comment]
When you're ready to try it out OS X, push the source and I can see if I can get it to compile and test it on iterm2.

**Comment by o-sdn-o** [comment]
Thank you for your attention to the project. This is a good motivation for work when the project is interesting not only for the developers themselves.

The situation here is a little more complicated than just building for a specific platform. The VTM project depends on the Desktopio TUI Engine, which is the engine that powers all the UI and rendering in the VTM. Desktopio is being developed from scratch as a standalone project without any dependencies and has never been published anywhere. At the moment, it is not clear whether the TUI concept is a relic of the past and should be forgotten in favor of the GUI, or simply its potential has not yet been fully revealed. The VTM should clarify this and show the Desktopio Engine perspective. Its source code will be published in the individual repository of the NetXS-Group.

The VTM source code in this repository will end up with the following structure:
- `vtmd.cpp` - desktop environment server, forms a shared environment for each account in the system, is responsible for creating instances of applications. Every connected user is a kind of desktop application, this concept provides a multi-user architecture of the desktop environment
- `vtm.cpp` - an intermediary between the physical terminal and the desktop server, its task is to unify I/O operations with the physical terminal
- `terminal.h` - header-only file with the Term application class - this is a terminal emulator built into VTM
- `/os/system.h` - header-only file with IPC abstraction classes and physical terminal I/O functionality, be it POSIX-terminal or classic windows command prompt
- `/os/file_system.h` - header-only file with functions for abstraction of file I/O of the platform used, whether it is GNU/Linux, Windows, etc.; is required to manage configuration files
- `install.sh` - installation script for Linux system
- `install.ps1` - installation script in Windows OS
- `vtm.conf` - config file template

**Comment by Nanoc-ice** [comment]
Thank you for the clarification, that provides the details I was interested in.  And while I am knowingly in the minority, I like the TUI as I do my work from the command line and text based tools.  So, providing a similar environment to GUI without the requirements of a GUI would provide an environment that I could be more productive with and look forward to being able to use this in both OSX environment as well as Linux (I don’t do ms windows).

**Comment by o-sdn-o** [comment]
The Desktopio Framework architecture is mature enough. Everything is now clear and the concept should not change significantly in the future. Research has ended and it remains to refine it to an acceptable state. All aspects cannot be completed alone in a reasonable amount of time. Any help is greatly appreciated.

Projects:
- VTM
	- a text-based desktop, aka Monotty Desktop (virtual terminal multiplexer)
- Desktopio Framework (namespace nexts::)
	- framework for creating terminal applications
		- Events (C++)
		- Keyboard/Mouse
		- Unicode text
		- ANSI VT parsing
		- and everything else that is needed for text and UI processing

At the moment, everything is published by one project - VTM, since many changes are expected, and the changes concern both VTM and Desktopio at the same time. Then Desktopio Framework will be separated into an independent project, in order to make it more convenient to use in other projects, I think there will be no problems with this, since there are no dependencies.

Note: everything is in an unfinished state and is a testing ground for experiments. Everything is as messy as you can afford it when experimenting.
