### ISSUE TITLE
add plugin system

### ISSUE THREAD

**Issue by Sertonix** [netxs-group/vtm#335]
A system to add plugins would be nice.
They could add applications or just modify the behavior.
With a good api it might even be possible to add more complex things like a better integration into a specific terminal.
Plugins could be added to the server or the client depending on what they do.

Maybe the default application could also be plugins so the size of the main client/server is reduced.

**Comment by o-sdn-o** [comment]
I think that the application level plugin system is not needed for vtm for the following reasons:
- Of the built-in applications, only one will remain - the built-in terminal. It can be replaced by any other by changing the main menu items in the configuration.
- Any DirectVT application running inside the vtm is seamlessly integrated into the environment as much as possible, as if it were a UI element of the environment itself, despite the fact that this application is a separate process in the OS. For example, you can uncomment `project ("calc")` and `add_executable (calc "netxs/apps/calc.cpp")`, compile calc(.exe) and play with it in dtvt mode, or just run it as `vtm -r calc`.
- Desktop with main menu and floating windows is also a built-in vtm application. It is relatively primitive, it can be rewritten to your taste and it will be your new vtm.
- What an application can do inside the vtm environment depends solely on the DirectVT protocol. Here, to expand the capabilities of the protocol, some plugins may be needed. For example, audio output support. We will think about this when we port Doom.
- Output to the external terminal of the final picture uses a minimum of VT-sequences, nothing that would require additional integration. When we enter the GUI field, the need for an external terminal will disappear by itself.
- Each dtvt-application will carry the code of both the server and the client. Due to this, each such application will be a multi-user vtm in itself. Interprocess communication there again will be using DirectVT.
- DirectVT can only output to one canvas so far, but support for output to any number of windows will be implemented soon, this is required to display custom modal windows by the application.

**Comment by o-sdn-o** [comment]
For me at the moment vtm is more than a desktop environment with a side menu and windows.
If we talk exclusively about the desktop with floating windows, then perhaps this should be considered as a separate application, or maybe this is the vtm itself in fact. Who knows. This is still a gray area.

**Comment by Sertonix** [comment]
Seems like a plugin system would cause more harm then use.
