### ISSUE TITLE
terminal specific configurations

### ISSUE THREAD

**Issue by Sertonix** [netxs-group/vtm#336]
Depending on the Terminal you might want to have different configurations.
For example you might want to use different colors if the terminal supports more or less.
It would be nice to define these configurations without starting vtm with a specific config file.

This could prevent things like #329

**Comment by o-sdn-o** [comment]
I'm sorry that I don't answer for a long time. I do not ignore, I was very puzzled in finishing the directvt mode. There are still a few things left to do. This is the remaining debt that came up when I gave up everything to implement my own "ConPTY" on Windows (Windows Console API Server) four months ago because it blocked all further development.

**Comment by Sertonix** [comment]
No problem.
I am currently busy with my own projects.

**Comment by o-sdn-o** [comment]
At first I thought that it would be nice to unify support for the 16-color mode (make it configurable or so), since it is hard-coded and suboptimal, but after thinking more, I decided that we should not bother with color support for individual terminals for the following reasons:

- Inside vtm everything is only truecolor and translation in 16 colors is hardcoded.
- vtm uses minimal vt functionality and assumes truecolor by default, distinguishing only a couple of 16-color terminals.
- All terminals will sooner or later support truecolor (as well as grapheme clusters). As a last resort, the built-in vtm terminal will soon become a cross-platform GUI application with support for this goodness.
- Support for 16-color mode is only suitable for emergency cases (Linux Console/Windows 8), for everyday use it is difficult to make it usable.

I probably don't know some special cases like Linux Console, if there is such knowledge I would be glad to know.

**Comment by Sertonix** [comment]
Ok I think that is ok.
If somebody wants better 16 colors integration they could just modify the client.
